remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: jSoboil
description: Website of Joshua Soboil
show_downloads: true
github:
  is_project_page: true
  repository_url: https://github.com/jSoboil