title: jSoboil
description: I like to meander and paint, but I seem to have a real shtick for health economics
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
github:
  is_project_page: true
  repository_url: https://github.com/jSoboil