title: jSoboil
description: I like to meander and paint, but I seem to have a real shtick for health economics
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
url: https://github.com/jSoboil/jSoboil.github.io
github:
  is_project_page: true
  repository_name: jSoboil
  repository_url: https://github.com/jSoboil